# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 338)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(25, 15, 25, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.points = QtWidgets.QLabel(self.centralwidget)
        self.points.setMaximumSize(QtCore.QSize(1000, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.points.setFont(font)
        self.points.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.points.setObjectName("points")
        self.verticalLayout.addWidget(self.points)
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setMaximumSize(QtCore.QSize(1000, 59))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(31)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.subject_check = QtWidgets.QLineEdit(self.centralwidget)
        self.subject_check.setMinimumSize(QtCore.QSize(0, 47))
        self.subject_check.setText("")
        self.subject_check.setObjectName("subject_check")
        self.verticalLayout.addWidget(self.subject_check)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label.setStyleSheet("color: rgb(255, 5, 9)")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.points.setText(_translate("MainWindow", "Баллов: {points}"))
        self.title.setText(_translate("MainWindow", "Введите предмет"))
        self.pushButton.setText(_translate("MainWindow", "Начать игру"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(705, 343)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonYes = QtWidgets.QPushButton(Form)
        self.pushButtonYes.setObjectName("pushButtonYes")
        self.gridLayout.addWidget(self.pushButtonYes, 1, 0, 1, 1)
        self.pushButtonNo = QtWidgets.QPushButton(Form)
        self.pushButtonNo.setObjectName("pushButtonNo")
        self.gridLayout.addWidget(self.pushButtonNo, 1, 1, 1, 1)
        self.questLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.questLabel.setFont(font)
        self.questLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.questLabel.setObjectName("questLabel")
        self.gridLayout.addWidget(self.questLabel, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonYes.setText(_translate("Form", "Да"))
        self.pushButtonNo.setText(_translate("Form", "Нет"))
        self.questLabel.setText(_translate("Form", "TextLabel"))
